source 'https://rubygems.org'


gem 'rails', '4.2.5.1'
gem 'rails-api'
gem 'pg'
gem 'rack-cors', :require => 'rack/cors'
gem 'active_model_serializers', '~> 0.8.3'

group :development, :test do
	gem 'rspec-rails'
	gem 'factory_girl_rails'
	gem 'faker'
	gem 'spring'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'selenium-webdriver'
end